[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  included_files = ["dist/server/**", "dist/_next/static/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs" 