[build]
  command = "./build.sh"
  publish = ".next"
  
[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"

[functions]
  included_files = ["dist/server/**", "dist/_next/static/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs" 