"""Add api_key to user model

Revision ID: f49e1cd5adc6
Revises: 07912eed9e00
Create Date: 2025-04-24 11:30:33.738707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49e1cd5adc6'
down_revision = '07912eed9e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
